### PR TITLE
Update to version 4.12

### PR DESCRIPTION
**Pull request by tadeu**

### CODE REVIEW

**Comment by tadeu** [comment]
Still there are compilation errors. I've [created an issue](https://github.com/CGAL/cgal-swig-bindings/issues/102) in CGAL/cgal-swig-bindings with the error.

Update: I've closed the issue, it was just that the recipe was using an older version of `cgal-swig-bindings`. Updating that it compiled ok.

**Comment by jschueller** [comment]
You shouldnt update the boost pin yet (or update it in every feedstock that doesnt use cb3 and propose the update in conda-forge-pinning-feedstock). Else you wont be able to install packages that rely on boost 1.66 simultaneously.

**Comment by tadeu** [comment]
@jschueller, what if we build two versions of CGAL 4.12: build number 0 with Boost 1.66 and build number 1 with Boost 1.67?

**Comment by jschueller** [comment]
That would work, but I'd prefer all the boost pinnings of all feedstocks to be updated at the same time.

**Comment by jschueller** [comment]
In fact, when we switch to conda-smithy 3, we wont even need to pin directly in the recipe:
https://conda-forge.org/docs/meta.html#pinning-packages

**Comment by tadeu** [comment]
> (or update it in every feedstock that doesnt use cb3 and propose the update in conda-forge-pinning-feedstock)

@jschueller, do you know a simple way to list these feedstocks?

**Comment by jschueller** [comment]
yes, type "boost-cpp 1.66" or "boost 1.66" in the github search bar of the conda-forge org (on the top left of the page https://github.com/conda-forge), then click Code tab, which shows we have eg 17 recipes depending on boost-cpp:
https://github.com/search?q=org%3Aconda-forge+boost-cpp+1.66&type=Code

**Pull request merged**
