### PR TITLE
Add support for CGAL_AABB_tree

### LINKED ISSUE #55: DLL Load failed in 4.14
I get a `dll load failed` error for the newest version (4.14) in a fresh environment. See also [this so post](https://stackoverflow.com/questions/60862979/modulenotfound-error-after-sucessfully-install-cgal-using-conda/60864038#60864038) Steps to reproduce on my windows 10 x64 system:
```
conda create -n cgalpython -c conda-forge python=3.7 cgal==4.14
conda activate cgalpython
python
>>> import CGAL
>>> print(CGAL.__version__)
4.14.0
>>> import CGAL.CGAL_AABB_tree
Traceback (most recent call last):
  File "C:\Users\<username>\.conda\envs\cgalpython\lib\site-packages\CGAL\CGAL_AABB_tree.py", line 14, in swig_import_helper
    return importlib.import_module(mname)
  File "C:\Users\<username>\.conda\envs\cgalpython\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 670, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 583, in module_from_spec
  File "<frozen importlib._bootstrap_external>", line 1043, in create_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
ImportError: DLL load failed: The specified module could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\<username>\.conda\envs\cgalpython\lib\site-packages\CGAL\CGAL_AABB_tree.py", line 17, in <module>
    _CGAL_AABB_tree = swig_import_helper()
  File "C:\Users\<username>\.conda\envs\cgalpython\lib\site-packages\CGAL\CGAL_AABB_tree.py", line 16, in swig_import_helper
    return importlib.import_module('_CGAL_AABB_tree')
  File "C:\Users\<username>\.conda\envs\cgalpython\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named '_CGAL_AABB_tree'
```

Note that this results in no error:
```
conda create -n test -c conda-forge python=3.7 cgal==4.13
conda activate test
python
>>> import CGAL.CGAL_AABB_tree
>>> import CGAL
>>> print(CGAL.__version__)
4.13.0
>>> import CGAL.CGAL_AABB_tree
```
<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list -n cgalpython
# packages in environment at C:\Users\<username>\.conda\envs\cgalpython:
#
# Name                    Version                   Build  Channel
boost-cpp                 1.70.0               h6a4c333_2    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
cgal                      4.14             py37hb1a71c1_0    conda-forge
cgal-cpp                  4.14.1               h411bc12_0    conda-forge
eigen                     3.3.7             he980bc4_1001    conda-forge
mpfr                      4.0.2                h2fa13f4_0    conda-forge
mpir                      3.0.0             he025d50_1002    conda-forge
openssl                   1.1.1e               hfa6e2cd_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
python                    3.7.6           h60c2a47_5_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.34.2                     py_1    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
```
The working one:
```
$conda list -n test
# packages in environment at C:\Users\<username>\.conda\envs\test:
#
# Name                    Version                   Build  Channel
boost-cpp                 1.69.0            h6a4c333_1001    conda-forge
ca-certificates           2019.11.28           hecc5488_0    conda-forge
certifi                   2019.11.28       py37hc8dfbb8_1    conda-forge
cgal                      4.13             py37h6538335_1    conda-forge
cgal-cpp                  4.13                 hbb34a18_1    conda-forge
mpfr                      4.0.2                h2fa13f4_0    conda-forge
mpir                      3.0.0             he025d50_1002    conda-forge
openssl                   1.1.1e               hfa6e2cd_0    conda-forge
pip                       20.0.2                     py_2    conda-forge
python                    3.7.6           h60c2a47_5_cpython    conda-forge
python_abi                3.7                     1_cp37m    conda-forge
setuptools                46.1.3           py37hc8dfbb8_0    conda-forge
sqlite                    3.30.1               hfa6e2cd_0    conda-forge
vc                        14.1                 h0510ff6_4
vs2015_runtime            14.16.27012          hf0eaf9b_1
wheel                     0.34.2                     py_1    conda-forge
wincertstore              0.2                   py37_1003    conda-forge
zlib                      1.2.11            h2fa13f4_1006    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$conda info

     active environment : test
    active env location : C:\Users\<username>\.conda\envs\test
            shell level : 2
       user config file : C:\Users\<username>\.condarc
 populated config files : C:\Users\<username>\.condarc
          conda version : 4.8.2
    conda-build version : not installed
         python version : 3.7.1.final.0
       virtual packages : __cuda=10.1
       base environment : C:\ProgramData\Miniconda3  (read only)
           channel URLs : https://repo.anaconda.com/pkgs/main/win-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/win-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://repo.anaconda.com/pkgs/msys2/win-64
                          https://repo.anaconda.com/pkgs/msys2/noarch
          package cache : C:\ProgramData\Miniconda3\pkgs
                          C:\Users\<username>\.conda\pkgs
                          C:\Users\<username>\AppData\Local\conda\conda\pkgs
       envs directories : C:\Users\<username>\.conda\envs
                          C:\ProgramData\Miniconda3\envs
                          C:\Users\<username>\AppData\Local\conda\conda\envs
               platform : win-64
             user-agent : conda/4.8.2 requests/2.22.0 CPython/3.7.1 Windows/10 Windows/10.0.17134
          administrator : False
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by tadeu**
fixes #55

Checklist
* [x] Used a fork of the feedstock to propose changes
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tadeu** [comment]
@conda-forge-admin, please rerender

**Comment by tadeu** [comment]
Having this issue in this build: https://github.com/CGAL/cgal-swig-bindings/issues/133

**Comment by tadeu** [comment]
Weird, the latest passing build is not reproducible anymore, it's still having the same error... perhaps we'll have to update it first, and solve those other issues that appeared...

**Comment by lrineau** [comment]
Hi @tadeu, let me help you. I am the CGAL release manager.

The bug https://github.com/CGAL/cgal-swig-bindings/issues/133 has been fixed directly in CGAL, in versions 4.14.3 and 5.0.1. If you want to keep cgal-feedstock to CGAL-4.14.x, then pick version 4.14.3, that [I released  25 February 2020](https://www.cgal.org/2020/02/25/cgal4143/), or a later version (there is none, at the time of this comment).

**Comment by tadeu** [comment]
Ok, for now I think it's simpler to try to fix this together with the update to version 5.0.1 in #57

**Comment by tadeu** [comment]
Superseded by #57

**Pull request closed without merging**
