### PR TITLE
Update to v5.5.1.post202302251605 and python 3.11

### LINKED ISSUE #77: @conda-forge-admin please rerender
### Additional comment:

_No response_

### PR DESCRIPTION
**Pull request by xylar**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

closes #79
closes #78 
closes #77 
closes #75

### CODE REVIEW

**Review by lrineau — APPROVED** [review]
That looks good to me. I hope the CI tests will turn green.

**Comment by xylar** [comment]
Thanks for having a look, @lrineau

**Comment by xylar** [comment]
I missed all the work that @chrisburr did in #75.  That looks similar to here.

**Comment by xylar** [comment]
@conda-forge-admin, please rerender

**Comment by xylar** [comment]
OSX error is
```
import: 'CGAL.CGAL_Kernel'
Traceback (most recent call last):
  File "/Users/runner/miniforge3/conda-bld/cgal_1671102549884/test_tmp/run_test.py", line 5, in <module>
    import CGAL.CGAL_Kernel
  File "/Users/runner/miniforge3/conda-bld/cgal_1671102549884/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.8/site-packages/CGAL/CGAL_Kernel.py", line 15, in <module>
    from . import _CGAL_Kernel
ImportError: dlopen(/Users/runner/miniforge3/conda-bld/cgal_1671102549884/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.8/site-packages/CGAL/_CGAL_Kernel.so, 2): Library not loaded: @loader_path/../lib/libCGAL_Kernel_cpp.dylib
  Referenced from: /Users/runner/miniforge3/conda-bld/cgal_1671102549884/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/python3.8/site-packages/CGAL/_CGAL_Kernel.so
  Reason: image not found
```

@lrineau, any ideas?

**Comment by lrineau** [comment]
It does not really look like a problem from CGAL or the recipe. I have attempted a local build of `osx_64_numpy1.23python3.11.____cpython` and it worked. Is there a way to restart the CI?

**Comment by xylar** [comment]
@conda-forge-admin, please restart ci

**Comment by xylar** [comment]
@lrineau, sadly the error remains the same as before and I'm not going to be any use at fixing this.

**Comment by lrineau** [comment]
The osx issue is actually an upstream issue. I can reproduce it with a bare build of https://github.com/CGAL/cgal-swig-bindings on macOS: the issue is the loaderpath once the extension modules are installed.

Working on it...

**Comment by lrineau** [comment]
> The osx issue is actually an upstream issue. I can reproduce it with a bare build of [CGAL/cgal-swig-bindings](https://github.com/CGAL/cgal-swig-bindings) on macOS: the issue is the loaderpath once the extension modules are installed.
> 
> Working on it...

Might be fixed by https://github.com/CGAL/cgal-swig-bindings/commit/ddf5bf24316ac70c3f78f73c42013488d8da16fc. If the upstream CI is fine, I will publish a new release of https://github.com/CGAL/cgal-swig-bindings and update this PR.

**Comment by lrineau** [comment]
And there it is! :tada:

**Comment by xylar** [comment]
Great, thank you for working on this.

**Comment by xylar** [comment]
I'm not a maintainer but feel free to merge when you're ready.

**Comment by lrineau** [comment]
Sorry, I forgot that I somehow became a maintainer of that feedstock, a while ago. Thanks for your first pull-request @xylar. It really helped. The macOS issue was actually an upstream issue, and as an upstream develop I had to struggle to find a correct fix and release a new version of cgal-swig-bindings.

**Pull request merged**
