### PR TITLE
Update to 5.4

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
Fix #65

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
I'm not sure what's going on for the osx build:
```
In file included from /Users/runner/miniforge3/conda-bld/cgal_1646360695793/work/build/build-python/CGAL/CGAL_Voronoi_diagram_2PYTHON_wrap.cxx:3023:
In file included from /Users/runner/miniforge3/conda-bld/cgal_1646360695793/work/SWIG_CGAL/Voronoi_diagram_2/all_includes.h:9:
In file included from /Users/runner/miniforge3/conda-bld/cgal_1646360695793/work/SWIG_CGAL/Voronoi_diagram_2/Voronoi_diagram_2.h:10:
/Users/runner/miniforge3/conda-bld/cgal_1646360695793/work/SWIG_CGAL/Common/Macros.h:145:45: error: no type named 'reference' in 'std::iterator_traits<CGAL::VoronoiDiagram_2::Internal::Handle_adaptor<CGAL::VoronoiDiagram_2::Internal::Face<CGAL::Voronoi_diagram_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>, CGAL::Delaunay_triangulation_adaptation_traits_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>>, CGAL::Delaunay_triangulation_caching_degeneracy_removal_policy_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>>>>>>'
  typedef typename std::iterator_traits<I>::reference reference;
          ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~
/Users/runner/miniforge3/conda-bld/cgal_1646360695793/work/SWIG_CGAL/Common/Macros.h:156:10: note: in instantiation of template class 'SWIG_CGAL_Extract_data<CGAL::VoronoiDiagram_2::Internal::Handle_adaptor<CGAL::VoronoiDiagram_2::Internal::Face<CGAL::Voronoi_diagram_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>, CGAL::Delaunay_triangulation_adaptation_traits_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>>, CGAL::Delaunay_triangulation_caching_degeneracy_removal_policy_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>>>>> &, true>' requested here
typename SWIG_CGAL_Extract_data<T&>::reference
         ^
/Users/runner/miniforge3/conda-bld/cgal_1646360695793/work/SWIG_CGAL/Voronoi_diagram_2/Voronoi_diagram_handles_2.h:92:3: note: while substituting deduced template arguments into function template 'SWIG_CGAL_extract_data' [with T = CGAL::VoronoiDiagram_2::Internal::Handle_adaptor<CGAL::VoronoiDiagram_2::Internal::Face<CGAL::Voronoi_diagram_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>, CGAL::Delaunay_triangulation_adaptation_traits_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>>, CGAL::Delaunay_triangulation_caching_degeneracy_removal_policy_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>>>>>]
  SWIG_CGAL_FORWARD_CALL_AND_REF_0(Halfedge_wrapper,halfedge)
  ^
/Users/runner/miniforge3/conda-bld/cgal_1646360695793/work/SWIG_CGAL/Common/Macros.h:180:3: note: expanded from macro 'SWIG_CGAL_FORWARD_CALL_AND_REF_0'
  SWIG_CGAL_FORWARD_CALL_AND_REF_SCOPE_0(RET,NAME,NAME)
  ^
/Users/runner/miniforge3/conda-bld/cgal_1646360695793/work/SWIG_CGAL/Common/Macros.h:175:3: note: expanded from macro 'SWIG_CGAL_FORWARD_CALL_AND_REF_SCOPE_0'
  SWIG_CGAL_FORWARD_CALL_SCOPE_0(RET,NAME,INAME) \
  ^
/Users/runner/miniforge3/conda-bld/cgal_1646360695793/work/SWIG_CGAL/Common/Macros.h:165:15: note: expanded from macro 'SWIG_CGAL_FORWARD_CALL_SCOPE_0'
  {return RET(SWIG_CGAL_extract_data(this->get_data()).INAME());}
              ^
/Users/runner/miniforge3/conda-bld/cgal_1646360695793/work/build/build-python/CGAL/CGAL_Voronoi_diagram_2PYTHON_wrap.cxx:4841:24: note: in instantiation of member function 'Voronoi_face_wrapper_2<CGAL::Voronoi_diagram_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>, CGAL::Delaunay_triangulation_adaptation_traits_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>>, CGAL::Delaunay_triangulation_caching_degeneracy_removal_policy_2<CGAL::Delaunay_triangulation_2<CGAL::Epick>>>, SWIG_Triangulation_2::CGAL_Vertex_handle<CGAL::Delaunay_triangulation_2<CGAL::Epick>, Point_2>, SWIG_Triangulation_2::CGAL_Face_handle<CGAL::Delaunay_triangulation_2<CGAL::Epick>, Point_2>>::halfedge' requested here
      result = (arg1)->halfedge();
                       ^
```

Any ideas @conda-forge/cgal?

/cc @traversaro - you're a C++ expert, any clues?

**Comment by traversaro** [comment]
> /cc @traversaro - you're a C++ expert, any clues?

My random guess is that for that specifica compilation unit some strange compilation options are passed, can you try to enable verbose make execution with `-DCMAKE_VERBOSE_MAKEFILE:BOOL=ON`? Thanks!

**Comment by lrineau** [comment]
I think that is an upstream problem: the C++ code in https://github.com/CGAL/cgal-swig-bindings is not compatible with latest developments in libc++.

**Now I speak with the main author of https://github.com/CGAL/cgal-swig-bindings:**

@sloriot The issue is in [`SWIG_CGAL/Common/Macros.h`, line 145](https://github.com/CGAL/cgal-swig-bindings/blob/5750b98dd1f760ba5ab24662957c1e1438bde8bb/SWIG_CGAL/Common/Macros.h#L141-L147): `typename std::iterator_traits<I>::reference` for a `I` that is not an iterator but a handle (of type [`CGAL::VoronoiDiagram_2::Internal::Handle_adaptor`](https://github.com/CGAL/cgal/blob/c58ac97e93c838ebfb1e8adaf23ff4fd185dc8e4/Voronoi_diagram_2/include/CGAL/Voronoi_diagram_2/Handle_adaptor.h#L26)). That class template `Handle_adaptor` has:
```c++
  typedef void iterator_category;
```
and that does not interacts well with the implementation of `std::iterator_traits` from libc++.

I think we should remove that line 145 of `SWIG_CGAL/Common/Macros.h`, and use `decltype(auto)` instead of `reference` as the return type of the `operator()`.

**Comment by Tobias-Fischer** [comment]
@lrineau - should we try to add a patch here in the feedstock to see whether your suggestion fixes the issue?

**Comment by lrineau** [comment]
> @lrineau - should we try to add a patch here in the feedstock to see whether your suggestion fixes the issue?

I just tried and it does not work, because `SWIG_CGAL/Common/Macros.h` is processed by swig, and swig does not understand `decltype(auto)`.

**Comment by lrineau** [comment]
That seems to work with:
```patch
diff --git a/SWIG_CGAL/Common/Macros.h b/SWIG_CGAL/Common/Macros.h
index be97588..5dac59b 100644
--- a/SWIG_CGAL/Common/Macros.h
+++ b/SWIG_CGAL/Common/Macros.h
@@ -142,7 +142,7 @@ template <class T>
 struct SWIG_CGAL_Extract_data<T,true>
 {
   typedef typename boost::remove_cv< typename boost::remove_reference<T>::type >::type I;
-  typedef typename std::iterator_traits<I>::reference reference;
+  typedef typename I::reference reference;
   reference operator()(I t){return *t;}
 };
 
``` 

Should I push that patch as an upstream commit?

**Comment by Tobias-Fischer** [comment]
That would be fantastic :)

**Comment by Tobias-Fischer** [comment]
@conda-forge/cgal @lrineau - this is ready for review/merge

**Comment by Tobias-Fischer** [comment]
Kind reminder @tadeu @lrineau @maxGimeno

**Comment by lrineau** [comment]
Hi @Tobias-Fischer. I am sorry I had not answered, so far. I will explain why.

I am one of the upstream developers: a developer of the CGAL project. My daily job is to develop C++ code for CGAL, and I do not write Python code. My company has created and maintained the https://github.com/CGAL/cgal-swig-bindings but that project is not in our current priority. In the past weeks, I have tried to improved the situation of that project, and in particular:
  - make it compiles with recent clang versions,
  - make it compiles with recent CGAL versions,
  - and ultimately I would like to fix all the issues that are detected by the CI actions: https://github.com/CGAL/cgal-swig-bindings/actions.

I am not myself a user of conda (well... I am starting to use it in the continuous integration tests), and I know close to nothing about its rules. @tadeu made me a co-maintainer of this feedstock, but I do not feel I have enough knowledge to be be able to merge a pull-request. For example. I see that you made recent commits like https://github.com/conda-forge/cgal-feedstock/pull/68/commits/e4337716b5a95a194b04f28d380696774f65bb09, but I do not know if our has to trigger again a "rerender" (whatever that means) to follow the rules of the conda forge project.

So, I had not answered, because I felt it was more the role of @tadeu. @tadeu, can you please comment, and maybe merge this pull-request?

**Comment by Tobias-Fischer** [comment]
Thanks for your detailed comment @lrineau that all makes sense :)

@wolfv - the other maintainers are not responsive, any chance you could merge?

**Comment by tadeu** [comment]
Hi folks, sorry for the delay, I'm taking a look at these changes right now!

**Review by tadeu — APPROVED** [review]
Awesome work @Tobias-Fischer, thanks! Please feel free to open a PR adding yourself as a maintainer if you wish!

Also thanks for the input @lrineau and @traversaro!

**Comment by tadeu** [comment]
By the way, good to know about the improvements being done upstream in https://github.com/CGAL/cgal-swig-bindings, @lrineau. It would be really nice if `cgal-swig-bindings` incorporated the patch added here, and also if it provided versioned (tagged) releases, preferably synced with C++ CGAL, so that @regro-cf-autotick-bot could do it's work!

**Comment by lrineau** [comment]
> By the way, good to know about the improvements being done upstream in [CGAL/cgal-swig-bindings](https://github.com/CGAL/cgal-swig-bindings), @lrineau. It would be really nice if `cgal-swig-bindings` incorporated the patch added here, and also if it provided versioned (tagged) releases, preferably synced with C++ CGAL, so that @regro-cf-autotick-bot could do it's work!

Thanks. I agree the CGAL project should do better. At least, as it is today:
  - the aforementioned patch has been integrated (it was the second commit of the pull-request https://github.com/CGAL/cgal-swig-bindings/pull/208, now merged)
  - I have fixed all the CI tests,
  - and then now cgal-swig-bindings compiles with a complex test matrix:
    - on Windows, Linux, MacOS,
    - with Python versions 3.7.x to 3.10.x,
    - with CGAL-5.3, CGAL-5.4, and with the current version of CGAL `master` branch,
  - and the Python tests works with all the combinations of the test matrix.

As for the version... the current `setup.py` hardcodes version `5.1`!! (See https://github.com/CGAL/cgal-swig-bindings/blob/293f797b25595f7ed0c83cb86c39f12391fc91a6/setup.py#L393-L394)

The difficulty is that there are two "versions" involved when that Python module is build:
  - the version of CGAL,
  - and the version of https://github.com/CGAL/cgal-swig-bindings itself.

For the versioning of https://github.com/CGAL/cgal-swig-bindings, I propose the simple date-based versioning: from time to time, tag a version like `20220323`, encoding the date of the latest commit. But then, what should be the version of the Python module? I would like something like `5.4-rev20220323`, encoding both the CGAL version, and the revision of the bindings. But I do not know if, with setuptools, we can delay the declaration of the `version` until the build command has started.

**Comment by tadeu** [comment]
Awesome news!

> For the versioning of https://github.com/CGAL/cgal-swig-bindings, I propose the simple date-based versioning: from time to time, tag a version like `20220323`, encoding the date of the latest commit. But them, what should be the version of the Python module? I would like something like `5.4-rev20220323`, encoding both the CGAL version, and the revision of the bindings. But I do not know if, with setuptools, we can delay the declaration of the `version` until the build command has started.

It's not only `setuptools`, the conda package will use the version declared in the [`meta.yaml`](https://github.com/conda-forge/cgal-feedstock/blob/fe04a8490949c319cb0c22568f2bc01939ce485e/recipe/meta.yaml#L5) file, and if we want the bot to automatically update that, I think that `cgal-swig-bindings` versions should have tags like you described, e.g., `5.4.20220323`, `5.4.20220401`, `5.5.20220401`.

**Pull request merged**
