### PR TITLE
Use mpir on windows

### PR DESCRIPTION
**Pull request by xantares**

### CODE REVIEW

**Comment by edisongustavo** [comment]
Hello, @xantares I'm interested in getting this merged.
What can we do to get this merged?
Would you like me to recreate the PR and make sure that it works?
Thanks.

**Comment by xantares** [comment]
I thought it would not build at all but surprisingly it builds almost everywhere (except on py35/vc14/x64):
https://ci.appveyor.com/project/conda-forge/cgal-feedstock/build/1.0.7
Maybe there's a problem on x64 that my patch doesnt address correctly (especially the typedef change), anyway this must be proposed upstream.

If you want to play with this you can cherry-pick my changes to the recipes (not the rerender commit that conflicts), and then rerender with latest conda-smithy.

**Comment by edisongustavo** [comment]
Ok, I will do that then and open a new PR.

**Comment by edisongustavo** [comment]
> this must be proposed upstream.

I tried doing that already: https://github.com/CGAL/cgal/issues/439

Which was refused :/

**Comment by xantares** [comment]
they refused to do it themselves, but you can still fix my patch and propose it to cgal

**Comment by lrineau** [comment]
@xantares I am sorry we refused the PR CGAL/cgal#439. I have no idea how difficult it would be to support MPIR on Windows but I think it will not be trivial. We have never tried, and we lack resources to find time to even try. Remember that we need to support GMP, so the support of MPIR would be a user-choice. Probably using a CMake configuration option. We would be glad if you manage to add that option into CGAL.

**Pull request closed without merging**
