### PR TITLE
Bump version to 4.14.2 and add build for Python 3.8

### PR DESCRIPTION
**Pull request by ostrokach**
Checklist
* [x] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by tadeu** [comment]
I've just merged a PR with version 5.0 of `cgal-cpp`, would you like to try again a PR for that version?

**Comment by ostrokach** [comment]
> I've just merged a PR with version 5.0 of `cgal-cpp`, would you like to try again a PR for that version?

My goal was to create a `cgal` build for Python 3.8. However, judging by the CI tests that are run, this is still Python <=3.7 only.

Do you have any idea how to upgrade packages to a newer Python version?

**Comment by tadeu** [comment]
They are all built at the same time (Pythons 3.6, 3.7 and 3.8, and Python 2.7 if not skipped). You can try creating a new PR that updates `cgal-cpp` to 5.0 and also updates the git hash of the Python bindings to the latest one compatible with 5.0, and let's see what happens:

https://github.com/conda-forge/cgal-feedstock/blob/cb132ad8220861915a5fdb920785ffb5d8bf7f66/recipe/meta.yaml#L8 

(this one here don't have Python 3.8 probably because it's old)

**Comment by ostrokach** [comment]
Updating to version 4.41.1 or 5.0 appears to be blocked by CGAL/cgal-swig-bindings#133 and CGAL/cgal#4355.

**Comment by tadeu** [comment]
Nice, thanks for looking into this @ostrokach 
Their latest passing build seems to be from a month ago: https://travis-ci.org/CGAL/cgal-swig-bindings/builds

**Comment by tadeu** [comment]
Superseded by #57

**Pull request closed without merging**
